services:
  rex:
    image: valentinschabschneider/trusty-rex:0.2.0
    restart: unless-stopped
    depends_on:
      - db
    environment:
      API_KEY: ${API_KEY}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      DEFAULT_LOGBOOKS: ${DEFAULT_LOGBOOKS}
    ports:
      - 8000:80

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
