services:
  rex:
    image: valentinschabschneider/trusty-rex:0.2.0
    restart: unless-stopped
    depends_on:
      - db
    environment:
      API_KEY: ${API_KEY}
      POSTGRES_SERVER: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_LOGBOOKS: ${DEFAULT_LOGBOOKS}
    ports:
      - 8000:80

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
