"""Init

Revision ID: 1cbe38df0a0a
Revises: 
Create Date: 2025-01-26 03:26:16.599537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cbe38df0a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logbook',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logbook_key'), 'logbook', ['key'], unique=True)
    op.create_table('record_state',
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('logbook_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['logbook_id'], ['logbook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logbook_id', 'key', 'created_at', name='uq_record_state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_state')
    op.drop_index(op.f('ix_logbook_key'), table_name='logbook')
    op.drop_table('logbook')
    # ### end Alembic commands ###
